.TH "CBASE16" "1" "" "cbase16 VERSION" "cbase16"

.SH NAME
.B cbase16

.SH SYNOPSIS
\fBcbase16\fR [\fICOMMAND\fR]

.SH DESCRIPTION
\fBcbase16\fR is a blazing fast base16 colorscheme builder

.SH COMMAND

.HP
\fBupdate\fR
.br
fetch all necessary sources for building

.HP
\fBbuild\fR
.br
generate colorscheme templates

.HP
\fBhelp\fR
.br
display usage message
