.TH "CBASE16" "1" "" "cbase16 VERSION" "cbase16"

.SH NAME
.B cbase16 - a blazing fast base16 colorscheme builder

.SH SYNOPSIS
\fBcbase16\fR [\fICOMMAND\fR] [\fIOPTIONS\fR]

.SH COMMAND

.HP
\fBupdate\fR
.br
fetch all necessary sources for building

.HP
\fBbuild\fR
.br
generate colorscheme templates

.HP
\fBlist\fR
.br
list available schemes and templates

.HP
\fBversion\fR
.br
display version

.HP
\fBhelp\fR
.br
display usage message

.SH OPTIONS

.HP
\fB-c\fR
.br
specify cache directory

.HP
\fB-s\fR
.br
only build specified schemes when use in conjuction with the \fBbuild\fR command

.HP
\fB-t\fR
.br
only build specified templates when use in conjuction with the \fBbuild\fR command

.HP
\fB-S\fR
.br
only show schemes when use in conjuction with the \fBlist\fR command

.HP
\fB-T\fR
.br
only show templates when use in conjuction with the \fBlist\fR command

.HP
\fB-o\fR
.br
Specify output directory

.HP
\fB-r\fR
.br
list items in a single column
