.TH "CBASE16" "1" "" "cbase16 VERSION" "cbase16"

.SH NAME
.B cbase16

.SH SYNOPSIS
\fBcbase16\fR [\fICOMMAND\fR] [\fIOPTIONS\fR]

.SH DESCRIPTION
\fBcbase16\fR is a blazing fast base16 colorscheme builder

.SH COMMAND

.HP
\fBupdate\fR
.br
fetch all necessary sources for building

.HP
\fBbuild\fR
.br
generate colorscheme templates

.HP
\fBhelp\fR
.br
display usage message

.SH OPTIONS

.HP
\fB-s\fR
.br
only build specified schemes

.HP
\fB-t\fR
.br
only build specified templates

.HP
\fB-o\fR
.br
Specify output directory
